version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    ports:
      - "8080:8080"
    entrypoint: jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_DB:postgres
      - POSTGRES_PASSWORD:1460
    volumes:
      - "pg-data:/var/postgresql/data"

volumes:
  pg-data: { }